[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
commands = [
  "dotnet restore",
  "dotnet publish ComputerSystem.REST/ComputerSystem.REST.csproj -c Release -o out"
]

[start]
cmd = "cd out && ./ComputerSystem.REST --urls http://0.0.0.0:$PORT"